language: ruby

rvm:
  - 2.6.3
  - 2.5.5
  - 2.4.6
  - 2.3.8
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
matrix:
  exclude:
    - rvm: 2.3.8
      gemfile: gemfiles/rails_6.0.gemfile
    - rvm: 2.4.6
      gemfile: gemfiles/rails_6.0.gemfile

