language: ruby
rvm:
  - 2.3.0
  - 2.2.2

# Avoid some errors, and speed things up:
# https://github.com/bundler/bundler/issues/3558#issuecomment-171347979
# https://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

matrix:
  include:
    - rvm: 2.1.0
      gemfile: Gemfile.pre_ruby_2.2.2
